# ==========================================================
# Superstore Sales Analysis Report
# Author : Hongyang Song
# ==========================================================

import os
import pandas as pd
from datetime import datetime

from docx import Document
from docx.shared import Pt
from docx.shared import Inches
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

from config import IMAGE_DIR, REPORT_DIR, create_mysql_engine

# ==========================================================
# MySQL连接
# ==========================================================

engine = create_mysql_engine()

print("=" * 60)
print("Reading data from MySQL...")
print("=" * 60)

df = pd.read_sql("SELECT * FROM orders", engine)

print("Data Shape:", df.shape)

# ==========================================================
# 创建Report文件夹
# ==========================================================

REPORT_PATH = REPORT_DIR
IMAGE_PATH = IMAGE_DIR

os.makedirs(REPORT_PATH, exist_ok=True)

# ==========================================================
# 自动统计指标
# ==========================================================

total_sales = df["Sales"].sum()
avg_sales = df["Sales"].mean()
max_sales = df["Sales"].max()
min_sales = df["Sales"].min()

order_count = df["Order ID"].nunique()
customer_count = df["Customer ID"].nunique()
product_count = df["Product Name"].nunique()

top_category = (
    df.groupby("Category")["Sales"]
      .sum()
      .idxmax()
)

top_region = (
    df.groupby("Region")["Sales"]
      .sum()
      .idxmax()
)

# ==========================================================
# 创建Word文档
# ==========================================================

doc = Document()

title = doc.add_heading(
    "Superstore Sales Analysis Report",
    level=0
)

title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

# ==========================================================
# 作者
# ==========================================================

author = doc.add_paragraph()

author.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

author.add_run(
    "Author: Hongyang Song\n"
).bold = True

author.add_run(
    "Generated by Python + MySQL\n"
)

author.add_run(
    datetime.now().strftime("%Y-%m-%d")
)

doc.add_page_break()

# ==========================================================
# Executive Summary
# ==========================================================

heading = doc.add_heading(
    "Executive Summary",
    level=1
)

p = doc.add_paragraph()

p.add_run("Dataset Overview\n").bold = True

p.add_run(f"• Total Orders: {order_count}\n")
p.add_run(f"• Total Customers: {customer_count}\n")
p.add_run(f"• Total Products: {product_count}\n")

p.add_run(f"• Total Sales: ${total_sales:,.2f}\n")
p.add_run(f"• Average Sales: ${avg_sales:,.2f}\n")
p.add_run(f"• Maximum Sales: ${max_sales:,.2f}\n")
p.add_run(f"• Minimum Sales: ${min_sales:,.2f}\n")

p.add_run(f"• Best Category: {top_category}\n")
p.add_run(f"• Best Region: {top_region}\n")

doc.add_page_break()

print("√ Cover Page Created")

# ==========================================================
# Business Overview
# ==========================================================

doc.add_heading("Business Overview", level=1)

doc.add_paragraph(
    "This report analyzes the Superstore sales dataset stored in MySQL. "
    "The dataset contains sales transactions from different regions, "
    "customer segments and product categories."
)

doc.add_paragraph(
    f"The dataset includes {len(df):,} sales records, "
    f"{order_count:,} unique orders, "
    f"{customer_count:,} customers "
    f"and {product_count:,} products."
)

doc.add_paragraph(
    f"Total sales reached ${total_sales:,.2f}. "
    f"The highest-selling category is {top_category}, "
    f"while the best-performing region is {top_region}."
)

doc.add_page_break()

# ==========================================================
# Figure 1
# ==========================================================

doc.add_heading("Figure 1. Monthly Sales Trend", level=1)

doc.add_picture(
    os.path.join(IMAGE_PATH, "monthly_sales.png"),
    width=Inches(6.5)
)

doc.add_paragraph(
    "The monthly sales trend illustrates how sales changed over time. "
    "This chart helps identify seasonal patterns and business growth."
)

doc.add_page_break()

# ==========================================================
# Figure 2
# ==========================================================

doc.add_heading("Figure 2. Sales by Category", level=1)

doc.add_picture(
    os.path.join(IMAGE_PATH, "category_sales.png"),
    width=Inches(6.5)
)

doc.add_paragraph(
    "Technology generates the highest sales among all product categories, "
    "followed by Furniture and Office Supplies."
)

doc.add_page_break()

# ==========================================================
# Figure 3
# ==========================================================

doc.add_heading("Figure 3. Sales by Region", level=1)

doc.add_picture(
    os.path.join(IMAGE_PATH, "region_sales.png"),
    width=Inches(6.5)
)

doc.add_paragraph(
    "The regional sales comparison indicates that the West region contributes "
    "the highest revenue, while the South region records the lowest sales."
)

doc.add_page_break()

print("√ Business Overview Completed")
print("√ First Three Figures Added")

# ==========================================================
# Figure 4
# ==========================================================

doc.add_heading("Figure 4. Sales by Customer Segment", level=1)

doc.add_picture(
    os.path.join(IMAGE_PATH, "segment_sales.png"),
    width=Inches(6.5)
)

doc.add_paragraph(
    "Consumer customers contribute the largest share of total sales, "
    "followed by Corporate and Home Office customers. "
    "This indicates that individual consumers remain the primary revenue source."
)

doc.add_page_break()

# ==========================================================
# Figure 5
# ==========================================================

doc.add_heading("Figure 5. Top 10 Products", level=1)

doc.add_picture(
    os.path.join(IMAGE_PATH, "top10_products.png"),
    width=Inches(6.5)
)

doc.add_paragraph(
    "The Top 10 products generate a significant proportion of total revenue. "
    "High-value products have a major impact on business performance."
)

doc.add_page_break()

# ==========================================================
# Figure 6
# ==========================================================

doc.add_heading("Figure 6. Sales Distribution", level=1)

doc.add_picture(
    os.path.join(IMAGE_PATH, "sales_distribution.png"),
    width=Inches(6.5)
)

doc.add_paragraph(
    "The sales distribution is right-skewed, indicating that most transactions "
    "are relatively small while a small number of orders contribute very high sales."
)

doc.add_page_break()

# ==========================================================
# Conclusion
# ==========================================================

doc.add_heading("Conclusion", level=1)

conclusion = doc.add_paragraph()

conclusion.add_run("Key Findings\n").bold = True

conclusion.add_run(
    f"• Total sales reached ${total_sales:,.2f}, demonstrating strong overall business performance.\n"
)

conclusion.add_run(
    f"• {top_category} is the best-performing product category.\n"
)

conclusion.add_run(
    f"• {top_region} generates the highest regional revenue.\n"
)

conclusion.add_run(
    "• Consumer customers contribute the largest proportion of sales.\n"
)

conclusion.add_run(
    "• Sales are highly concentrated in a small number of high-value products.\n"
)

conclusion.add_run(
    "• The sales distribution shows a typical long-tail pattern.\n"
)

conclusion.add_run(
    "• Future marketing efforts should focus on high-value products, customer retention, and regional optimization."
)

# ==========================================================
# Save Report
# ==========================================================

output_file = os.path.join(
    REPORT_PATH,
    "Superstore_Report.docx"
)

doc.save(output_file)

# ==========================================================
# Finish
# ==========================================================

print("\n" + "=" * 60)
print("Superstore Analysis Report Generated Successfully!")
print("=" * 60)

print(f"Report Path:\n{output_file}")

print("\nReport Includes:")
print("✓ Cover Page")
print("✓ Executive Summary")
print("✓ Business Overview")
print("✓ Monthly Sales Trend")
print("✓ Sales by Category")
print("✓ Sales by Region")
print("✓ Sales by Customer Segment")
print("✓ Top 10 Products")
print("✓ Sales Distribution")
print("✓ Conclusion")

print("\n★★★★★ Report Export Completed ★★★★★")
